# frozen_string_literal: true

source "https://rubygems.org"

gem 'rake'
gem 'thor'
gem 'chef'
gem 'json'
gem 'chefspec'
gem 'foodcritic'
gem 'knife-spork'
gem 'berkshelf'
gem 'knife-ec2'
gem 'knife-hp'
